### ISSUE TITLE
MQTT_SUBTOPICS doesn't work

### ISSUE THREAD

**Issue by jpopelka** [packit/packit-service-centosmsg#6]
In [centosmsg dc](https://github.com/packit-service/deployment/blob/master/openshift/packit-service-centosmsg.yml.j2#L51) we set
```yaml
env:
  - name: MQTT_SUBTOPICS
    value: pull-request
```

But, I see all kinds of subtopics in centosmg pod logs:
```
Received a message on topic: git.stg.centos.org/issue.comment.added
Received a message on topic: git.stg.centos.org/issue.edit
Received a message on topic: git.stg.centos.org/git.receive
Received a message on topic: git.stg.centos.org/git.branch.creation
Received a message on topic: git.stg.centos.org/commit.flag.added
```

**Comment by jpopelka** [comment]
Ah, right, so it's just `Received`, not `sent to Celery`.

**Comment by csomh** [comment]
> Ah, right, so it's just `Received`, not `sent to Celery`.

Yes, though the logging was indeed misleading. There is a somewhat longer explanation in the [README](https://github.com/packit-service/packit-service-centosmsg#mqtt_subtopics) why this has to be done this way.
